"""drop agent and reviewer photos

Revision ID: 62e387319b02
Revises: 92d12d797b4c
Create Date: 2026-10-04 16:09:01.436273

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62e387319b02"
down_revision: str | Sequence[str] | None = "92d12d797b4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "avatar_url")
    op.drop_column("reviews", "avatar_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("avatar_url", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("agents", sa.Column("avatar_url", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
